
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # ✅ CONST & PERFORMANCE
    prefer_const_constructors: true                         # Usa `const` siempre que se pueda.
    prefer_const_literals_to_create_immutables: true       # Usa `const` para listas/mapas inmutables.
    prefer_const_constructors_in_immutables: true           # Usa `const` en constructores inmutables.
    prefer_const_declarations: true                         # Declara variables como `const` cuando sea posible.

    # ✅ FLUTTER UI & LAYOUT
    sort_child_properties_last: true                        # `child:` debe ir al final del widget.
    avoid_unnecessary_containers: true                      # Evita usar Containers si no son necesarios.
    use_key_in_widget_constructors: true                    # Requiere que los widgets usen `Key` en el constructor.

    # ✅ ESTILO Y LEGIBILIDAD
    sort_constructors_first: true                           # Ordena constructores al inicio de la clase.
    sort_unnamed_constructors_first: true                   # Ordena constructores sin nombre antes que los con nombre.
    type_annotate_public_apis: true                         # Anota explícitamente el tipo en métodos públicos.
    always_declare_return_types: true                       # Requiere declarar el tipo de retorno.
    unnecessary_this: true                                  # Evita el uso innecesario de `this`.
    unnecessary_overrides: true                             # Evita sobreescribir métodos si no agregan valor.
    prefer_typing_uninitialized_variables: true             # Añade tipo a variables no inicializadas.
    omit_local_variable_types: false                        # Evita usar `var` en locales, usa tipos explícitos.

    # ✅ BUENAS PRÁCTICAS
    always_use_package_imports: true                        # Usa `package:` en lugar de rutas relativas.
    avoid_print: true                                       # Evita usar `print`, usa logs estructurados.
    avoid_empty_else: true                                  # Evita bloques `else` vacíos.
    prefer_final_locals: true                               # Usa `final` para variables locales.
    prefer_final_in_for_each: true                          # Usa `final` en bucles `forEach`.
    avoid_redundant_argument_values: true                   # Elimina valores redundantes en argumentos.
    unnecessary_late: true                                  # Evita el uso innecesario de `late`.

    # ✅ IMPORTS Y ORGANIZACIÓN
    require_trailing_commas: true                           # Requiere comas al final (útil para difs y formateo).
    depend_on_referenced_packages: true                     # Solo depende de paquetes que realmente uses.