name: btg_fund_manager
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  go_router: ^16.0.0
  kiwi: ^5.0.0
  json_annotation: ^4.9.0
  http: ^1.4.0
  intl: ^0.19.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  go_router_builder: ^3.0.1
  kiwi_generator: ^4.2.1
  json_serializable: ^6.7.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true