#!/bin/sh

COMMIT_MSG_FILE="$1"

# Filtrar líneas de comentario
MESSAGE=$(grep -v '^#' "$COMMIT_MSG_FILE" | tr -d '\n' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')

if ! echo "$MESSAGE" | grep -qE '^(Merge|feat|fix|docs|style|refactor|test|chore)(\(.+\))?: .+'; then
  echo "❌ Commit message must follow Conventional Commits."
  echo "💡 Example: feat(auth): add login validation"
  exit 1
fi

echo "✅ Commit message is valid."